const ilacCategory = {
  order: 17,
  name: "İlaç",
  slug: "ilac",
  iconKey: "pill",
  description: "İlaç firmaları ve biyoteknoloji markaları.",
  ctgry: ["Saç Bakım", "İlaç", "Eczane", "İlaç Şirketi", "Vitamin Takviyesi"],
  brands: [
    {
      name: "Bioblas",
      slug: "bioblas",
      foundedYear: 2008,
      ctgry: "Saç Bakım",
      founder: "Biota Laboratuvarları",
      owner: "Biota Laboratuvarları",
      country: "Türkiye",
      alternative_products: [],
      img: "/bioblas.png",
      isBoycotted: "boykot-degil",
      website: "https://bioblas.com/",
      description: `Bioblas, Türkiye merkezli bir saç bakım markasıdır. Marka, saç dökülmesine karşı bitkisel çözümler üretmek amacıyla 2008 yılında İstanbul'da Biota Laboratuvarları tarafından kurulmuştur. Biota, bitkisel içerikli ürünleriyle tanınan bir firmadır ve Bioblas, bu vizyonun en güçlü temsilcilerinden biridir.

2010 yılında kısa sürede Türkiye genelinde tanınmaya başlamış ve eczane kanallarında öne çıkmıştır. 2015 yılında Avrupa, Orta Doğu ve Asya pazarlarına açılarak uluslararası bir marka haline gelmiştir. 2020 ve sonrasında farklı saç tiplerine yönelik çözümler sunmaya devam etmektedir.

Bioblas, saç dökülmesi karşıtı formülleriyle öne çıkar ve ürünlerinde bitkisel özler kullanarak hem kadınlar hem de erkekler için saç sağlığını hedefler. Marka, Anadolu'nun zengin florasından güç alarak, Türk bilim insanları ve dermatologlarla iş birliği yaparak geliştirdiği ürünleri Türkiye genelindeki eczaneler ve parfümerilerde sunmaktadır.`,
    },
    {
      name: "Nobel",
      slug: "nobel",
      foundedYear: 1964,
      ctgry: "İlaç",
      founder: "Bilinmiyor",
      owner: "Ulkar Holding",
      country: "Türkiye",
      alternative_products: [],
      img: "/nobel.png",
      isBoycotted: "boykot-degil",
      website: "https://www.nobel.com.tr/",
      description: `Nobel, Türkiye merkezli uluslararası bir ilaç şirketidir. Şirketin kökenleri 1954 yılındaki farmasötik faaliyetlere dayanır ve 1964 yılında tamamen yerli sermayeli bir ilaç şirketi olarak kurulmuştur. "Sağlığa Değer" yaklaşımıyla üretim ve Ar-Ge yatırımları yaparak uluslararası bir ilaç şirketine dönüşmüştür.

Günümüzde Nobel, Ulkar Holding çatısı altında faaliyet göstermektedir. Türkiye'de Nobel İlaç, Kazakistan'da Nobel AFF ve Özbekistan'da Nobel Pharmsanoat olmak üzere üç ana şirketi bulunmaktadır. Toplamda 5 kampüs ve 11 üretim tesisi ile faaliyetlerini sürdürmektedir. Üretim tesislerinden üçü Türkiye'de, diğerleri Kazakistan ve Özbekistan'da yer almaktadır.

Nobel, 20'den fazla ülkede kendi organizasyonları aracılığıyla satış ve tanıtım faaliyetleri yürütmektedir. Yaklaşık 4.000 uzman çalışanı bulunmaktadır. Uluslararası standartlarda üretilen yüksek kaliteli ürünlerini 50'den fazla ülkeye ihraç etmektedir. Bu başarı, Türkiye'nin ilaç sektöründe dışa bağımlılığı azaltma stratejisine katkı sağlamaktadır. Nobel, on yılı aşkın süredir ihracat başarılarıyla Türkiye'nin ilaç sektöründeki dış ticaret dengesine olumlu katkıda bulunmaktadır.

Türkiye'deki Nobel İlaç, yaklaşık 2.500 çalışanıyla faaliyet göstermektedir. Üretim ve Ar-Ge faaliyetleri Düzce ve Gebze'de, hammadde üretimi ise Çerkezköy'deki tesislerinde gerçekleştirilmektedir. Nobel İlaç, stratejik öncelik olarak belirlediği biyoteknolojik ilaç üretimi ve Ar-Ge alanlarında yatırımlarına devam etmektedir.

Özbekistan'da Nobel Pharmsanoat ile ilk uluslararası adımını atan Nobel, bu ülkede yaptığı Ar-Ge ve üretim tesisi yatırımlarıyla Özbek halkına 80'den fazla marka ve 150'den fazla ilaç formu sunmakta ve komşu ülkelere ihracat yapmaktadır. Kazakistan'da 2002 yılında kurulan Nobel AFF, ülkenin ilk yabancı sermayeli üretim tesisini açmıştır. Nobel AFF, ülkenin en iyi yatırımcı ödülünü almış ve Kazakistan'da İyi Üretim Uygulamaları (GMP) sertifikasına sahip ilk şirkettir.

Nobel'in her girişimindeki temel hedefi, faaliyet gösterdiği ülkelerdeki toplumların sağlığına değer katmak ve ilaç tedarikinin sürdürülebilirliğini desteklemektir. Şirket, sağlık ekosisteminin ve ekonominin gelişimi için çalışmaya devam etmektedir.`,
    },
    {
      name: "Watsons",
      slug: "watsons",
      foundedYear: 1828,
      ctgry: "Eczane",
      founder: "Bilinmiyor",
      owner: "CK Hutchison Holdings Limited",
      country: "Çin",
      alternative_products: [],
      img: "/watsons.png",
      isBoycotted: "boykot",
      website: "https://www.watsons.com.tr/",
      description: `Watsons, Hong Kong merkezli bir kozmetik ve sağlık ürünleri şirketidir. Dünyanın en büyük sağlık ve güzellik zincirlerinden birisidir. 1841 yılında kurulan Watsons, A.S. Watson Group'a bağlıdır ve 25'ten fazla ülkede faaliyet göstermektedir. Avrupa ve Asya bölgesi başta olmak üzere dünyanın hemen hemen her bölgesinde mağazaları bulunmaktadır.

Watsons, Türkiye'de milyonlarca müşteriye sahiptir ve hemen hemen her şehirde şubesi bulunmaktadır. Şirket, kozmetik, kişisel bakım, sağlık ürünleri ve ilaç kategorilerinde geniş bir ürün yelpazesi sunmaktadır. CK Hutchison Holdings Limited'in sahibi olduğu Watsons, global bir perakende zinciri olarak faaliyetlerini sürdürmektedir.`,
      boycottReason: `Watsons, Çin'in Doğu Türkistan'daki insan hakları ihlalleri nedeniyle boykot çağrılarıyla karşı karşıyadır. Çin hükümetinin Uygur Türklerine karşı uyguladığı politikalar; zorla çalıştırma, kültürel soykırım ve diğer baskıcı eylemlerle dünya genelinde tepkilere neden olmaktadır. Doğu Türkistan bölgesinde üretildiği bilinen pek çok ürün, zorla çalıştırılan Uygurların emeğini içermektedir.

Watsons, Çin'in ekonomik ekosistemine bağlı bir şirket olarak, bu insanlık dışı uygulamalara dolaylı destek sağladığı gerekçesiyle eleştirilmektedir. Çin terör devletinin Uygur Türklerine karşı "nesli imha" ve "soykırım" politikası ile kültürel katliamın bir parçası olarak yürüttüğü bu sistem, Watsons'ın boykot edilmesinin temel nedenlerindendir. Watsons ve benzeri Çin merkezli şirketleri boykot etmek, Uygur Türkleri için bir destek niteliği taşımaktadır.`,
    },
    {
      name: "Bayer",
      slug: "bayer",
      foundedYear: 1863,
      founder: "Friedrich Bayer ve Johann Friedrich Weskott",
      owner:
        "Halka açık (%88,98), The Capital Group Companies Inc. (%10,02), Çalışanlar (%2,00)",
      ctgry: "İlaç Şirketi",
      country: "Almanya",
      alternative_products: [],
      img: "/bayer.png",
      isBoycotted: "boykot",
      website: "https://www.bayer.com.tr/tr/",
      description: `Bayer AG, Almanya merkezli çok uluslu bir ilaç ve biyoteknoloji şirketidir. Dünyanın en büyük ilaç ve biyomedikal şirketlerinden biridir. Şirket, 1 Ağustos 1863 tarihinde Barmen'de (şimdi Wuppertal'ın bir bölgesi) tüccar Friedrich Bayer ve boya ustası Johann Friedrich Weskott tarafından küçük bir boya malzemeleri fabrikası olarak kurulmuştur. Merkezi Leverkusen'de bulunmaktadır.

Bayer, ilaç, tüketici sağlığı ürünleri ve tarım kimyasalları alanlarında faaliyet göstermektedir. Şirket, EURO STOXX 50 borsa endeksinin bir bileşenidir. 1899 yılında Bayer, asetilsalisilik asit bileşiğini Aspirin ticari markası altında piyasaya sürmüştür. Aspirin, Dünya Sağlık Örgütü'nün Temel İlaçlar Listesi'nde yer almaktadır.

Bayer'in geniş bir ilaç portföyü bulunmaktadır. Şirket, birçok terapötik alanı kapsayan çok çeşitli ilaçlar sunmaktadır. Aspirin (asetilsalisilik asit), Xarelto (rivaroxaban), Nexavar (sorafenib), Betaseron (interferon beta-1b), Adalat (nifedipine), Yaz (drospirenone ve ethinylestradiol) ve Stivarga (regorafenib) gibi ürünler bunlardan sadece birkaçıdır. Şirket, yeni ilaçlar geliştirmeye devam etmektedir.`,
      boycottReason: `Bayer, İsrail'e verdiği destekler nedeniyle boykot edilmektedir. Şirketin CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
      subBrands: [
        {
          name: "Aspirin",
          slug: "aspirin",
          foundedYear: 1897,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/aspirin.png",
          isBoycotted: "boykot",
          website: "https://www.aspirin.com/",
          description: `Aspirin, asetilsalisilik asit içeren bir ilaçtır. 1897 yılında Almanya'da Bayer şirketi tarafından geliştirilmiştir. Aspirin, ağrı kesici, ateş düşürücü ve anti-inflamatuar özelliklere sahip bir nonsteroidal anti-inflamatuar ilaç (NSAID) olarak kullanılmaktadır. Ayrıca kalp krizi ve felç riskini azaltmak için düşük dozlarda antikoagülan olarak da kullanılmaktadır.
  
  Aspirin, dünya çapında en yaygın kullanılan ilaçlardan biridir ve Dünya Sağlık Örgütü'nün Temel İlaçlar Listesi'nde yer almaktadır. İlaç, Bayer şirketinin ticari markası olarak başlamış, ancak zamanla jenerik bir isim haline gelmiştir. Aspirin, ağrı, ateş ve iltihap tedavisinde yaygın olarak kullanılmaktadır.`,
          boycottReason: `Aspirin, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Aspirin" markası da boykot listemizdedir. Bayer'in İsrail'e yönelik desteği nedeniyle şirket ve ürünleri boykot edilmektedir.`,
        },
        {
          name: "Supradyn",
          slug: "supradyn",
          foundedYear: 1960,
          founder: "Bayer",
          ctgry: "Vitamin Takviyesi",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/supradyn.png",
          isBoycotted: "boykot",
          website: "https://www.supradyn.com.tr/",
          description: `Supradyn, Bayer şirketi tarafından üretilen bir multivitamin ve mineral takviyesi markasıdır. Farklı yaş ve ihtiyaç gruplarına yönelik çeşitli ürünleri bulunmaktadır. Supradyn ürünleri, enerji seviyelerini artırmak, bağışıklık sistemini desteklemek ve genel sağlığı iyileştirmek isteyen bireyler için tasarlanmıştır.

Supradyn ürün serisi, farklı yaş grupları ve özel ihtiyaçlar için formüle edilmiş çeşitli takviyeler içermektedir. Örneğin, Supradyn Energy 50+ 50 yaş ve üzeri bireyler için özel olarak formüle edilmiştir ve enerji metabolizmasını destekleyen B1, B2, B6 ve B12 vitaminleri ile hücreleri oksidatif stresten koruyan C ve E vitaminleri, çinko ve selenyum içerir. Supradyn, vitamin ve mineral takviyesi alanında dünya çapında tanınan bir markadır.`,
          boycottReason: `Supradyn, Bayer şirketine ait bir multivitamin ve mineral takviyesi markasıdır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Supradyn" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Rennie",
          slug: "rennie",
          foundedYear: 1931,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/rennie.png",
          isBoycotted: "boykot",
          website: "https://www.rennie.com.tr/",
          description: `Rennie, Bayer şirketi tarafından üretilen bir antasit ilaçtır. Mide asidi, mide yanması, hazımsızlık ve mide ekşimesi gibi sindirim problemlerinin tedavisinde kullanılmaktadır. Rennie, kalsiyum karbonat ve magnezyum karbonat içeren bir kombinasyon antasitidir.

Rennie, hızlı etkili bir antasit olarak bilinmektedir. Mide asidini nötralize ederek mide yanması ve hazımsızlık semptomlarını hızlı bir şekilde rahatlatır. Rennie, çiğnenebilir tablet formunda sunulmaktadır ve dünya çapında yaygın olarak kullanılan bir antasit markasıdır.`,
          boycottReason: `Rennie, Bayer şirketine ait bir antasit ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Rennie" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Diane",
          slug: "diane",
          foundedYear: 1970,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/diane.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Diane, Bayer şirketi tarafından üretilen bir doğum kontrol hapıdır. Hormonal kontraseptif olarak kullanılmaktadır.`,
          boycottReason: `Diane, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Diane" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Talcid",
          slug: "talcid",
          foundedYear: 1975,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/talcid.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Talcid, Bayer şirketi tarafından üretilen bir antasit ilaçtır. Mide asidi, mide yanması ve hazımsızlık tedavisinde kullanılmaktadır.`,
          boycottReason: `Talcid, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Talcid" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Yasminelle",
          slug: "yasminelle",
          foundedYear: 2000,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/yasminelle.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Yasminelle, Bayer şirketi tarafından üretilen bir doğum kontrol hapıdır. Hormonal kontraseptif olarak kullanılmaktadır.`,
          boycottReason: `Yasminelle, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Yasminelle" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Aktren",
          slug: "aktren",
          foundedYear: 1980,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/aktren.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Aktren, Bayer şirketi tarafından üretilen bir ağrı kesici ve anti-inflamatuar ilaçtır.`,
          boycottReason: `Aktren, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Aktren" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Alka Seltzer",
          slug: "alka-seltzer",
          foundedYear: 1931,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/alka-seltzer.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Alka Seltzer, Bayer şirketi tarafından üretilen bir antasit ve ağrı kesici ilaçtır. Mide yanması, hazımsızlık ve ağrı tedavisinde kullanılmaktadır.`,
          boycottReason: `Alka Seltzer, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Alka Seltzer" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Afrin",
          slug: "afrin",
          foundedYear: 1960,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/afrin.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Afrin, Bayer şirketi tarafından üretilen bir burun spreyi ve dekonjestan ilaçtır. Burun tıkanıklığı tedavisinde kullanılmaktadır.`,
          boycottReason: `Afrin, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Afrin" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Canesten",
          slug: "canesten",
          foundedYear: 1970,
          founder: "",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/canesten.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Canesten, Bayer şirketi tarafından üretilen bir antifungal (mantar önleyici) ilaçtır. Mantar enfeksiyonlarının tedavisinde kullanılmaktadır.`,
          boycottReason: `Canesten, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Canesten" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Elevit",
          slug: "elevit",
          foundedYear: 1980,
          founder: "",
          ctgry: "Vitamin Takviyesi",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/elevit.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Elevit, Bayer şirketi tarafından üretilen bir multivitamin ve mineral takviyesidir. Özellikle hamilelik öncesi ve hamilelik döneminde kadınların besin ihtiyaçlarını karşılamak için formüle edilmiştir.`,
          boycottReason: `Elevit, Bayer şirketine ait bir vitamin takviyesidir. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Elevit" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Glucobay",
          slug: "glucobay",
          foundedYear: 1990,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/glucobay.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Glucobay, Bayer şirketi tarafından üretilen bir diyabet ilacıdır. Tip 2 diyabet tedavisinde kullanılmaktadır.`,
          boycottReason: `Glucobay, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Glucobay" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Claritin",
          slug: "claritin",
          foundedYear: 1990,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/claritin.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Claritin, Bayer şirketi tarafından üretilen bir antihistaminik ilaçtır. Alerji semptomlarının tedavisinde kullanılmaktadır.`,
          boycottReason: `Claritin, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Claritin" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
        {
          name: "Iberogast",
          slug: "iberogast",
          foundedYear: 1960,
          founder: "Bayer",
          ctgry: "İlaç",
          owner: "Bayer",
          country: "Almanya",
          alternative_products: [],
          img: "/iberogast.png",
          isBoycotted: "boykot",
          website: "https://www.bayer.com.tr/tr/urunler",
          description: `Iberogast, Bayer şirketi tarafından üretilen bir bitkisel sindirim ilacıdır. Fonksiyonel sindirim bozuklukları ve irritabl bağırsak sendromu tedavisinde kullanılmaktadır.`,
          boycottReason: `Iberogast, Bayer şirketine ait bir ilaçtır. Bayer şirketi, İsrail'e verdiği destekler sebebiyle boykot listesinde olduğu için "Iberogast" markası da boykot listemizdedir. Bayer'in CEO'su Bill Anderson, savaşın ilk günlerinde yaptığı bir açıklamada Hamas'ı terör örgütü olarak kınamış ve İsrail halkına desteğini açıklamıştır. Bayer, Almanya'daki merkezinde İsrail bayrakları asarak İsrail'e desteğini kamuoyuna açıkça ilan etmiştir. Bu sebepler, firmanın boykot edilmesi için yeterlidir.`,
        },
      ],
    },
    {
      name: "Nurofen",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "",
      slug: "",
      foundedYear: 2141242412,
      founder: "safsaf",
      owner: "safsa",
      country: "Türkiye",
      alternative_products: [],
      img: "/file.png",
      isBoycotted: "onerilmiyor",
      website: "",
      description: ``,
      boycottReason: ``,
    },
  ],
};

export default ilacCategory;
