const modaCategory = {
  order: 10,
  name: "Moda",
  slug: "moda",
  iconKey: "gem",
  description: "Lüks ve tasarım odaklı moda markaları.",
  brands: [
    {
      name: "Boyner",
      slug: "boyner",
      foundedYear: 1952,
      ctgry: "E-ticaret",
      founder: "Boyner Ailesi",
      owner: "Cem Boyner",
      country: "Türkiye",
      alternative_products: [],
      img: "/boyner.png",
      isBoycotted: "boykot-degil",
      website: "https://www.boyner.com.tr/",
      description: `Boyner Holding, merkezi İstanbul'da bulunan bir holding kuruluşudur. Grup, ağırlıklı olarak perakende olmak üzere, tekstil ve konfeksiyon üretimi ile gayrimenkul sektörlerinde faaliyetlerini sürdürmektedir.

Holdingin kökenleri, 1952 yılında Altınyıldız Mensucat ve Konfeksiyon Fabrikaları A.Ş.'nin kurulmasına dayanır; bu şirket holdingin ilk şirketi olarak kabul edilir. Boyner Ailesi tarafından kurulan grubun Yönetim Kurulu Başkanı Cem Boyner'dir.

Boyner Grup, Türkiye'nin önde gelen mağaza ve moda perakendesi gruplarından biridir. Bünyesinde 6 grup şirketi, 250'den fazla mağaza, e-ticaret siteleri ve mobil uygulamalar bulundurur. Grup, 8.000'i aşkın çalışanıyla geniş bir operasyonel ağa sahiptir.`,
    },

    {
      name: "Modanisa",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "LC Waikiki",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "Decathlon",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "FLO",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "Koton",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "Mavi",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "DeFacto",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "E-Bebek",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
    {
      name: "Sefamerve / Lidyana",
      slug: "",
      foundedYear: 2008,
      ctgry: "E-ticaret",
      founder: "",
      owner: "",
      country: "",
      alternative_products: [],
      img: "/.png",
      isBoycotted: "boykot",
      website: "",
      description: ``,
      boycottReason: ``,
    },
  ],
};

export default modaCategory;
