const oyunCategory = {
  order: 31,
  name: "Oyun",
  slug: "oyun",
  iconKey: "gamepad-2",
  description: "Video oyunları ve donanım sağlayıcıları.",
  ctgry: ["Oyun Platformu", "Oyun Çözümü", "Oyun Stüdyosu", "Oyun"],
  brands: [
    {
      name: "Steam",
      slug: "steam",
      description: `Valve'ın kurucu ortakları Gabe Newell ve Mike Harrington tarafından 1996'da kurulan şirket, 2003'te Steam'i duyurarak dijital oyun dağıtımında devrim yarattı. Platform; oyun güncellemelerini otomatikleştiren istemcisi, 125 milyondan fazla kullanıcıya ulaşan topluluk araçları ve erken erişim programıyla bağımsız stüdyolar için en görünür vitrinlerden biri hâline geldi.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://store.steampowered.com/",
      img: "/oyun.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Valve ABD merkezlidir; boykot kriterlerimiz uyarınca ABD merkezli platformları desteklemiyoruz.`,
    },
    {
      name: "Epic Games",
      slug: "epic-games",
      description: `Tim Sweeney tarafından 1991'de Cary, Kuzey Karolina'da kurulan Epic Games, Unreal Engine teknolojisiyle oyun geliştirmede standart belirledi. 2018'de açılan Epic Games Store; ücretsiz hafta içeriği, geliştirici dostu gelir paylaşımı modeli ve Fortnite'ın 2017'den beri devam eden başarısıyla ekosistemini büyütüyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://store.epicgames.com/",
      img: "/epic-games.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Epic Games ABD merkezli bir şirkettir; ABD bağlantısı nedeniyle boykot listemize dahildir.`,
    },
    {
      name: "Xbox Game",
      slug: "xbox-game",
      description: `1975'te Bill Gates ve Paul Allen tarafından kurulan Microsoft, 2001'de ilk Xbox konsolunu satışa çıkararak ev konsolu pazarına girdi. Xbox Game markası; Game Pass (2017) aboneliği, bulut oyun çözümü xCloud ve 23 stüdyodan oluşan Xbox Game Studios ağıyla Microsoft'un oyun ekosisteminin kalbini oluşturuyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.xbox.com/",
      img: "/xbox-game.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Xbox, Microsoft'un ABD merkezli oyun markasıdır; ABD bağlantısı sebebiyle boykottadır.`,
    },
    {
      name: "GOG (Good Old Games)",
      slug: "gog",
      description: `Marcin Iwiński ve Michał Kiciński'nin 1994'te kurduğu CD Projekt, 2008'de GOG markasını hayata geçirerek klasik PC oyunlarını DRM'siz biçimde yeniden yayımlamaya başladı. Platform bugün; The Witcher serisi gibi CD Projekt yapımlarının yanı sıra bağımsız stüdyolara kuratörlü destek veren vitrinleri ve topluluk forumlarıyla Avrupa merkezli alternatif bir dağıtım kanalı sunuyor.`,
      country: "Polonya",
      website: "https://www.gog.com/",
      img: "/gog.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot-degil",
      boycottReason: `ABD veya İsrail bağlantısı bulunmadığından boykot uygulanmıyor.`,
    },
    {
      name: "Origin (EA App)",
      slug: "origin",
      description: `Trip Hawkins'in 1982'de kurduğu Electronic Arts, 2011'de Origin'i (2022'de EA App olarak yenilendi) piyasaya sürerek dijital satışı kendi çatısı altında topladı. Uygulama; EA Play aboneliği, bulut kayıt desteği, FIFA ve Battlefield gibi serilere yönelik erken erişimler ve Windows ile macOS istemcileriyle yayıncı ekosisteminin merkezinde yer alıyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.ea.com/ea-app",
      img: "/origin.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Electronic Arts ABD merkezlidir; bu nedenle platformu boykot listemize ekliyoruz.`,
    },
    {
      name: "Ubisoft Connect",
      slug: "ubisoft-connect",
      description: `Beş Guillemot kardeşin 1986'da Fransa'da kurduğu Ubisoft, 2009'da Uplay olarak başlattığı platformu 2020'de Ubisoft Connect adıyla yeniden konumlandırdı. Hizmet; Assassin's Creed, Rainbow Six ve Just Dance serilerinde çapraz ilerleme, bulut kayıt desteği, ödül sistemi ve Ubisoft+ aboneliğiyle küresel topluluğa entegre edilmiş bir oyun ekosistemi sunuyor.`,
      country: "Fransa",
      website: "https://ubisoftconnect.com/",
      img: "/ubisoft-connect.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot-degil",
      boycottReason: `Merkezi Fransa'dadır ve ABD/İsrail bağlantısı yoktur; boykot uygulanmaz.`,
    },
    {
      name: "Battle.net",
      slug: "battle-net",
      description: `Allen Adham, Frank Pearce ve Mike Morhaime tarafından 1991'de kurulan Blizzard Entertainment, 1996'da Battle.net'i Diablo ile birlikte hizmete açtı. Platform; Overwatch, World of Warcraft ve Call of Duty gibi markalara tek hesap üzerinden erişim, bölgesel e-spor yayınları ve 7/24 güncellenen sosyal hub yapısıyla Blizzard ekosisteminin omurgasını oluşturuyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.blizzard.com/",
      img: "/battle-net.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Blizzard Entertainment ABD merkezlidir; ABD bağlantısı nedeniyle boykot kapsamındadır.`,
    },
    {
      name: "Microsoft Store / Xbox App",
      slug: "microsoft-store-xbox-app",
      description: `1975'te kurulan Microsoft, 2012'de Windows Store'u duyurup ekosistemi 2015'te Xbox App ile pekiştirdi. Windows 10/11 entegrasyonu, Xbox Game Pass yönetimi, Xbox Series konsollarıyla senkronize sosyal özellikler ve Play Anywhere programıyla kullanıcıların kütüphanesini cihazlar arasında sorunsuz taşımayı hedefliyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.microsoft.com/store/apps",
      img: "/microsoft-store-xbox-app.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Microsoft ABD merkezli bir teknoloji şirketidir; ABD bağlantısı sebebiyle boykot edilir.`,
    },
    {
      name: "itch.io",
      slug: "itch-io",
      description: `Leaf Corcoran tarafından 2013'te başlatılan itch.io, gelir paylaşımını geliştiricinin belirlediği açık modelle tanındı. Ludum Dare gibi game jam topluluklarını destekleyen platform; mobil, masaüstü ve tarayıcı projelerini barındıran esnek altyapısıyla bağımsız sahnenin deneysel oyunlarına ev sahipliği yapıyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://itch.io/",
      img: "/itch-io.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Platform ABD merkezlidir; ABD bağlantısı sebebiyle boykot listemizde yer alır.`,
    },
    {
      name: "Humble Bundle",
      slug: "humble-bundle",
      description: `Jeff Rosen ve John Graham'ın 2010'da San Francisco'da başlattığı Humble Bundle, 'öde-bilinçli' paket sistemiyle hayır kurumlarına yüz milyonlarca dolar aktardı. Bugün Humble Choice aboneliği, DRM'siz Humble Trove arşivi ve bağımsız stüdyoları destekleyen yayıncılık koluyla içerik üreticilerini küresel ölçekte öne çıkarıyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.humblebundle.com/",
      img: "/humble-bundle.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Humble Bundle ABD merkezlidir; ABD bağlantısı nedeniyle boykot kapsamındadır.`,
    },
    {
      name: "Amazon Games / Prime Gaming",
      slug: "amazon-games-prime-gaming",
      description: `Jeff Bezos'un 1994'te kurduğu Amazon, 2012'de Amazon Game Studios adıyla oyun geliştirmeye adım attı ve 2020'de Twitch Prime'ı Prime Gaming olarak yeniden markaladı. Bölgesel stüdyoları (Orange County, Montreal) aracılığıyla New World ve Lost Ark gibi projelere yatırım yaparken, Prime üyelerine her ay ücretsiz oyunlar ve oyun içi içerikler sunuyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://gaming.amazon.com/",
      img: "/amazon-games-prime-gaming.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Amazon ABD merkezlidir ve İsrail ile ticari ilişkileri vardır; bu nedenle boykot edilir.`,
    },
    {
      name: "Rockstar Games Launcher",
      slug: "rockstar-games-launcher",
      description: `Sam ve Dan Houser kardeşler ile Terry Donovan tarafından 1998'de kurulan Rockstar Games, 2019'da Rockstar Games Launcher'ı tanıtarak PC kataloğunu tek çatı altında topladı. Uygulama; Social Club entegrasyonu, bulut tabanlı kayıt senkronizasyonu ve Grand Theft Auto ile Red Dead Redemption serileri için özel indirim/bonus kampanyalarıyla yayınevine bağlı oyuncu topluluğunu güçlendiriyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://socialclub.rockstargames.com/rockstar-games-launcher",
      img: "/rockstar-games-launcher.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Rockstar Games, ABD merkezli Take-Two çatısı altındadır; ABD bağlantısı nedeniyle boykot edilir.`,
    },
    {
      name: "PUBG",
      slug: "pubg",
      description: `Güney Kore merkezli Krafton (2007'de Chang Byung-gyu tarafından kurulan Bluehole'un yeniden yapılanmış hâli), Brendan "PlayerUnknown" Greene'in geliştirdiği moddan esinlenerek 2017'de PUBG: Battlegrounds'u yayınladı. 2021'de ücretsiz oynanışa geçiş yapan yapım; PC, konsol ve mobil sürümleriyle dünya genelinde espor turnuvaları ve içerik sezonlarıyla büyüyor.`,
      country: "Güney Kore",
      website: "https://na.battlegrounds.pubg.com/",
      img: "/pubg.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Doğu Türkistan'da Yaşananlar Sebebi Ile Çin'e Ait Global Markaların Tamamı BOYKOT Listemizdedir.`,
    },
    {
      name: "Fifa",
      slug: "fifa",
      description: `EA Sports stüdyosu, 1993'te FIFA International Soccer ile başlattığı seride dünya futbol federasyonlarıyla geniş lisans anlaşmaları yaptı. Redwood City merkezli ekip; Frostbite motoru, Ultimate Team modu (2009) ve eSpor turnuvalarıyla seriyi 30 yılı aşkın süredir canlı tutarken 2023 itibarıyla markayı EA SPORTS FC adıyla dönüştürme sürecine girdi.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.ea.com/games/fifa",
      img: "/fifa.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `FIFA serisini geliştiren EA Sports, ABD merkezli Electronic Arts'a aittir; bu nedenle boykot listemizdedir.`,
    },
    {
      name: "GTA",
      slug: "gta",
      description: `Grand Theft Auto serisi, 1997'de İskoçya merkezli DMA Design tarafından başlatıldı ve stüdyo 2002'de Rockstar North adına dönüştürüldü. Sam ve Dan Houser'ın kreatif liderliğinde 2001'de GTA III ile 3D açık dünya formülüne geçildi; serinin bölgesel uyarlamaları, sinematik anlatımı ve çevrimiçi modu GTA Online (2013) ile dünya çapında devasa bir topluluk oluştu.`,
      country: "Birleşik Krallık (Rockstar North)",
      website: "https://www.rockstargames.com/",
      img: "/gta.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Serinin geliştiricisi Birleşik Krallık merkezli olsa da marka ABD merkezli Take-Two Interactive/Rockstar Games'e aittir; ABD bağlantısı sebebiyle boykot edilir.`,
    },
    {
      name: "Minecraft",
      slug: "minecraft",
      description: `Markus "Notch" Persson tarafından 2009'da geliştirilmeye başlanan Minecraft, Mojang Studios'un 2011'de resmi çıkışıyla bağımsız bir fenomene dönüştü. Stockholm merkezli stüdyo 2014'te Microsoft tarafından satın alındı; bugün eğitim sürümü, Realms sunucuları ve yaratıcı topluluğu destekleyen Marketplace ile milyonlarca oyuncuya yaşayan bir sandbox evreni sunuyor.`,
      country: "İsveç / Amerika Birleşik Devletleri",
      website: "https://www.minecraft.net/",
      img: "/minecraft.png",
      isBoycotted: "boykot",
      ctgry: "Oyun",
      boycottReason: `Oyun Mojang tarafından İsveç'te geliştirilse de stüdyo 2014'ten beri ABD merkezli Microsoft'a aittir; bu sahiplik nedeniyle boykot kapsamındadır.`,
    },
    {
      name: "Counter‑Strike",
      slug: "counter-strike",
      description: `Counter-Strike, 1999'da Minh Le ve Jess Cliffe'in Half-Life modu olarak geliştirmesiyle ortaya çıktı; Valve 2000'de projeyi satın alarak seriyi resmileştirdi. CS:GO (2012) ve Source 2 tabanlı Counter-Strike 2 (2023), e-spor ligleri, atölye içerikleri ve taktiksel oynanışıyla rekabetçi FPS kültürünün simgelerinden biri oldu.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.counter-strike.net/",
      img: "/counter-strike.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Counter-Strike'ın sahibi Valve ABD merkezlidir; ABD bağlantısı nedeniyle boykot edilir.`,
    },
    {
      name: "League of Legends",
      slug: "league-of-legends",
      description: `Brandon Beck ve Marc Merrill'in 2006'da Los Angeles'ta kurduğu Riot Games, 2009'da League of Legends'ı yayımlayarak MOBA türünü erişilebilir hâle getirdi. Oyun; 2015'te tamamı Tencent'e geçen Riot'un LCS, LEC, Worlds gibi espor ekosistemi, sürekli güncellenen şampiyon havuzu ve Runeterra evrenini genişleten medya projeleriyle büyümesini sürdürüyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.leagueoflegends.com/",
      img: "/league-of-legends.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Riot Games'in ana merkezi ABD'dedir; ABD bağlantısı sebebiyle boykot kapsamındadır.`,
    },
    {
      name: "Fortnite",
      slug: "fortnite",
      description: `Epic Games'in Unreal Engine 4 teknolojisiyle geliştirdiği Fortnite, 2017'de Save the World olarak erken erişime çıktı ve aynı yıl Battle Royale modu ile küresel fenomen oldu. Düzenli sezon güncellemeleri, 2020'de gelen Kreatif 2.0 araçları ve Travis Scott ile Ariana Grande gibi markalı canlı etkinlikleriyle oyun, dijital kültürü şekillendiren bir sosyal platform hâline geldi.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.fortnite.com/",
      img: "/fortnite.png",
      ctgry: "Oyun Stüdyosu",
      isBoycotted: "boykot",
      boycottReason: `Epic Games ABD merkezlidir; bu nedenle Fortnite markası boykot listemize girer.`,
    },
    {
      name: "Call of Duty",
      slug: "call-of-duty",
      description: `Activision (1979'da David Crane ve arkadaşları tarafından kuruldu) ile Infinity Ward'un işbirliği sonucu 2003'te başlayan Call of Duty, II. Dünya Savaşı temalı kampanyalarla çıkış yaptı. Seri yıllar içinde Modern Warfare, Black Ops ve Warzone alt markalarıyla her yıl düzenli lansmanlar, espor ligleri ve çapraz platform destekleriyle büyüyerek Activision Blizzard portföyünün amiral gemisi oldu.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.callofduty.com/",
      img: "/call-of-duty.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Activision Blizzard ABD merkezlidir; ABD bağlantısı nedeniyle boykot kapsamındadır.`,
    },
    {
      name: "Valorant",
      slug: "valorant",
      description: `Riot Games, 2020'de kapalı betasını başlattığı Valorant ile CS benzeri taktiksel oynanışı kahraman yetenekleriyle birleştirdi. Los Angeles ve Dublin stüdyolarının geliştirdiği yapım; Vanguard anti-hile sistemi, bölgesel liglere ayrılmış espor takvimi ve düzenli ajan/harita güncellemeleriyle küresel rekabet sahnesine yön veriyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://playvalorant.com/",
      img: "/valorant.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Riot Games'in ABD merkezli olması nedeniyle Valorant boykot listemizde yer alır.`,
    },
    {
      name: "Overwatch",
      slug: "overwatch",
      description: `Blizzard Entertainment, Titan kod adlı iptal edilen MMO projesinden elde ettiği tecrübeyle 2016'da Overwatch'u dünyaya tanıttı. Jeff Kaplan liderliğinde geliştirilen yapım; Overwatch League (2018), düzenli hikâye etkinlikleri ve 2022 çıkışlı Overwatch 2 ile kahraman tabanlı nişancı türünde kalıcı bir iz bıraktı.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://overwatch.blizzard.com/",
      img: "/overwatch.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Blizzard Entertainment ABD merkezli olduğundan Overwatch boykot kapsamındadır.`,
    },
    {
      name: "World of Warcraft",
      slug: "world-of-warcraft",
      description: `World of Warcraft, Blizzard'ın 2004'te Warcraft III evrenini çevrimiçi RPG'ye taşımasıyla doğdu. Chris Metzen ve Jeff Kaplan gibi yaratıcı ekip üyelerinin imzasını taşıyan oyun; 10'dan fazla genişleme paketi, WoW Classic sürümleri (2019) ve dünya çapında düzenlenen BlizzCon etkinlikleriyle MMORPG geleneğini 20 yılı aşkın süredir yaşatıyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://worldofwarcraft.blizzard.com/",
      img: "/world-of-warcraft.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `Blizzard Entertainment ABD merkezlidir; ABD bağlantısı nedeniyle boykot edilir.`,
    },
    {
      name: "World of Tanks",
      slug: "world-of-tanks",
      description: `Wargaming, Victor Kislyi tarafından 1998'de Minsk'te kuruldu ve 2010'da World of Tanks'i hizmete açtı. Merkezi bugün Kıbrıs'ta bulunan şirket; 600'den fazla tarihsel tank modelini içeren oyunla küresel turnuvalar düzenliyor, oyuncu klanları için strateji araçları ve düzenli güncelleme planıyla hizmet veriyor.`,
      country: "Kıbrıs",
      website: "https://worldoftanks.com/",
      img: "/world-of-tanks.png",
      ctgry: "Oyun",
      isBoycotted: "boykot-degil",
      boycottReason: `Wargaming'in merkez üssü Kıbrıs'tadır; ABD veya İsrail bağlantısı bulunmaz.`,
    },
    {
      name: "Roblox",
      slug: "roblox",
      description: `David Baszucki ve Erik Cassel tarafından 2004'te geliştirilmeye başlanan Roblox, 2006'da halka açılan sürümüyle kullanıcı tarafından oluşturulan oyunların merkezi oldu. Roblox Studio araç seti, sanal ekonomi Robux ve eğitim kurumlarına yönelik Creator Hub'ı sayesinde milyonlarca genç geliştiricinin projelerini yayınladığı devasa bir metaverse ekosistemi sunuyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.roblox.com/",
      img: "/roblox.png",
      ctgry: "Oyun Platformu",
      isBoycotted: "boykot",
      boycottReason: `Roblox Corporation ABD merkezlidir; ABD bağlantısı nedeniyle boykot edilir.`,
    },
    {
      name: "Football Manager",
      slug: "football-manager",
      description: `Paul ve Oliver Collyer kardeşlerin 1994'te Londra'da kurduğu Sports Interactive, 2004'te Football Manager adıyla yeni serisini başlattı ve 2006'da Sega çatısı altına katıldı. 50 binden fazla gerçek oyuncuyu kapsayan veri tabanı, antrenman modelleme araçları ve her yıl gelen lisans genişlemeleriyle futbol taktik tutkunlarına derin bir kariyer deneyimi sunuyor.`,
      country: "Birleşik Krallık",
      website: "https://www.footballmanager.com/",
      img: "/football-manager.png",
      ctgry: "Oyun",
      isBoycotted: "boykot-degil",
      boycottReason: `Yapımın sahibi Sports Interactive Birleşik Krallık merkezlidir; ABD/İsrail bağlantısı yoktur.`,
    },
    {
      name: "EA SPORTS FC™",
      slug: "ea-sports-fc",
      description: `Electronic Arts'ın 30 yıllık futbol serisi, 2023'te FIFA lisansından ayrılarak EA SPORTS FC markasına dönüştü. EA Vancouver ve EA Romanya stüdyoları; HyperMotion V teknolojisi, kadın futbol ligleri ve Ultimate Team kulüp kimliği güncellemeleriyle yeni dönemi desteklerken, şirketin 1982'de Trip Hawkins tarafından ABD'de kurulan kökleri abonelik ve canlı hizmet modellerini şekillendiriyor.`,
      country: "Amerika Birleşik Devletleri",
      website: "https://www.ea.com/games/ea-sports-fc",
      img: "/ea-sports-fc.png",
      ctgry: "Oyun",
      isBoycotted: "boykot",
      boycottReason: `EA Sports, ABD merkezli Electronic Arts'ın markasıdır; ABD bağlantısı nedeniyle boykottadır.`,
    },
  ],
};

export default oyunCategory;
